on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          pip install Cython mypy
      - name: Compile the code
        run: |
          python setup.py build_ext --inplace
      - name: Run tests
        id: tests
        run: |
          python main.py
      - name: Run mypy
        id: mypy
        run: |
          mypy .
        continue-on-error: true
      - name: Comment mypy errors
        if: ${{ github.event_name == 'pull_request' && steps.mypy.outcome == 'failure' }}
        uses: actions/github-script@v4
        env:
          MYPY_OUTPUT: "${{ steps.mypy.outputs.stderr }}\n${{ steps.mypy.outputs.stdout }}"
        with:
          script: |
            body = `### ❌ Mypy Error
            <details><summary>Error Message</summary>
            <p>

            \`\`\`\n
            >> mypy
            ${{ process.env.MYPY_OUTPUT }}
            \`\`\`

            </p>
            </details>`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
